const tasks=[{id:1,title:"Implementar autenticação JWT",category:"Desenvolvimento",type:"dev",status:"done"},{id:2,title:"Modelar entidade de usuário",category:"Desenvolvimento",type:"dev",status:"progress"},{id:3,title:"Estudar Spring Security",category:"Estudos",type:"study",status:"todo"},{id:4,title:"Documentar endpoints da API",category:"Planejamento",type:"plan",status:"progress"},{id:5,title:"Criar tela de login",category:"Design",type:"design",status:"done"},{id:6,title:"Configurar banco de dados",category:"Desenvolvimento",type:"dev",status:"done"}];
const labels={todo:"A fazer",progress:"Em andamento",done:"Concluída"};
let current="all";
const list=document.querySelector("#taskList");
function render(){const filtered=tasks.filter(t=>current==="all"||t.status===current);list.innerHTML=filtered.map(t=>`<div class="task-row"><button class="check ${t.status==="done"?"done":""}" data-id="${t.id}" aria-label="Alternar tarefa">${t.status==="done"?"✓":""}</button><div class="task-info"><strong>${t.title}</strong><small>${labels[t.status]} · ${t.category}</small></div><span class="tag ${t.type}">${t.category}</span></div>`).join("");updateStats()}
function updateStats(){const total=tasks.length,done=tasks.filter(t=>t.status==="done").length,progress=tasks.filter(t=>t.status==="progress").length;document.querySelector("#total").textContent=total;document.querySelector("#done").textContent=done;document.querySelector("#progress").textContent=progress;document.querySelector("#rate").textContent=Math.round(done/total*100)+"%";document.querySelector("#rateBar").style.width=done/total*100+"%"}
list.addEventListener("click",e=>{const btn=e.target.closest(".check");if(!btn)return;const task=tasks.find(t=>t.id==btn.dataset.id);task.status=task.status==="done"?"todo":"done";render()});
document.querySelectorAll(".filter").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(b=>b.classList.remove("active"));btn.classList.add("active");current=btn.dataset.filter;render()}));
const dialog=document.querySelector("#taskDialog");document.querySelector("#newTaskBtn").onclick=()=>dialog.showModal();
document.querySelector("#taskForm").addEventListener("submit",e=>{e.preventDefault();const title=document.querySelector("#title").value.trim();const category=document.querySelector("#category").value;if(!title)return;const type=category==="Estudos"?"study":category==="Design"?"design":category==="Planejamento"?"plan":"dev";tasks.unshift({id:Date.now(),title,category,type,status:"todo"});dialog.close();e.target.reset();render()});
document.querySelector("#menuBtn").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
render();